### PR TITLE
Fixes for Android build

### PR DESCRIPTION
**Pull request by RubenGarcia**
Remove signed/unsigned error
(https://github.com/Zintinio/HappyHTTP/pull/15)
Fix initialization order error
Fix unused variable error

### CODE REVIEW

**Comment by mryonts** [comment]
Ruben, I just cloned this repository and it fails to compile out of the box on Mac and Windows.  Have you tried building recently on a clean machine?  Development machines always work because undocumented dependencies exist; but clean machines have a bit of struggle.  Thanks

**Comment by Zintinio** [comment]
@mryonts I'll check right now, push a fix if I can reproduce.

**Comment by RubenGarcia** [comment]
No, I have not used git pull for a while on this project

**Comment by Zintinio** [comment]
@mryonts the problem (as far as I can tell) was a windows-specific fix submitted as a pull-request. I didn't do my due diligence out of lazyness and broke the library. I've reverted the changes and I've managed to build / run on macOS thus far. Let me know if you're able to get things working on Android / Linux / Mac. I'm sorry to say that Windows support is not a priority and that I might end up cutting a platform out to make this project easier to maintain.

**Comment by mryonts** [comment]
@Zintinio I appreciate such fast response!  I cloned the project to my Mac and it compiles and runs properly.  The only issue there is that tests 2 and 3 give me 405 errors, but I do not care about that.  I will worry about taking this code and making it work on Windows as I need.  Again, much appreciated.

**Pull request merged**
