### PR TITLE
inet_addr

### PR DESCRIPTION
**Pull request by goldbattle**
This is my solution for the deprecated `inet_addr` method.

Took most of the code from here:
http://www.geekpage.jp/en/programming/winsock/getaddrinfo-0.php

### CODE REVIEW

**Comment by Zintinio** [comment]
Thanks, I'll look into this as soon as I can.

**Comment by Zintinio** [comment]
I'll be merging this in later today, I only just now remembered! Thanks.

**Comment by codecat** [comment]
How about mering this now? :+1:

**Comment by Zintinio** [comment]
@codecat I have no Windows system to verify this on currently. You are welcome to verify this.

**Comment by codecat** [comment]
This works after linking with `ws2_32.lib` and commenting out the `inet_addr` call:

	// First try nnn.nnn.nnn.nnn form
	/*
	saddr.s_addr = inet_addr(address);
	if (saddr.s_addr != -1)
		return &saddr;
	*/

**Comment by Zintinio** [comment]
@codecat works for me.

**Pull request merged**
